import { z } from "zod";

/**
 * Timing Manifest Schema
 *
 * Defines the structure for per-tutorial timing.json files generated by the TTS pipeline.
 * Remotion compositions consume this manifest to calculate frame counts and sequence audio.
 */

export const TimingEntrySchema = z.object({
  /** Step identifier matching the tutorial script, e.g. "step-001" */
  stepId: z.string(),
  /** Relative path to the audio file, e.g. "step-001.wav" */
  audioFile: z.string(),
  /** Duration of the audio clip in milliseconds */
  durationMs: z.number(),
  /** Original narration text used to generate the audio */
  narration: z.string(),
  /** Word count of the narration text */
  wordCount: z.number(),
});

export const TimingManifestSchema = z.object({
  /** Per-step timing entries in script order */
  steps: z.array(TimingEntrySchema),
  /** Sum of all step durations in milliseconds */
  totalDurationMs: z.number(),
  /** TTS engine used for generation */
  engine: z.enum(["kokoro", "chatterbox"]),
  /** ISO 8601 timestamp of when this manifest was generated */
  generatedAt: z.string(),
});

export type TimingEntry = z.infer<typeof TimingEntrySchema>;
export type TimingManifest = z.infer<typeof TimingManifestSchema>;
